apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: practicioner-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2JqQ0NBVllDQVFBd0tURVZNQk1HQTFVRUF3d01jSEpoWTNScFkybHZibVZ5TVJBd0RnWURWUVFLREFkcwpaV0Z5Ym1WeU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd0p3aHhjK3pmbUQ2Cnp6UVNua1pmSU9US3R3Z3dyVFJINW1Pa1RqSnEyMkNjZDhncm41Ym5paFFRb01CYmF1OUV0TDdlOHArSzJWVzQKV25PWCtvZlBadTNiL3BOOVpndVV0WkpneGRyT0ZYdll4ME53bDd3Tk8wUXFtUk8vR2hHZEt1QWxna1N5di82bgo2UWprdW85T000VWFaaTlrQzZIT3VEd2Z3OTVGWWplajRnUEhaSVc4NFp0MmM4ei9iaVo3QUJNcVB2VjE4N3VNCjJwZVQzTjBZaUFjRWgzT1ZRdmFwR2tIZ1RSQWV1blZHSFozYVBrdFJ3aG5oZW9ZS1dEbGR2SjVCTGpoVUZHUkcKWXZXR20xUGtaYkNMMUNHYW11eFNsbXQ4VlhTRjFrRFUwblNBTW9XZ3kxeTdjeDIwYXlrT0VOdlVWZDd2V3piTApGSSt1eExTODNRSURBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDVFF0cTRKRUkyUjVqMEI2NDRICjM1U3dlTVFubXcrRkVrNFBIWi9WTklTWlF5VmNPY2FFdEkyTDhtam9kOW9pRWpxWkZ0WXRuTW1ZRC9PL3FNYWEKb0w3bW4xd1B2S2hyRFFHeGxDeXU3Z3I2ZWU1RDlXV094M1k5RWQ0dXhwWnE5ckxJMk5QK0pRdEMyWWR2MW9PcQpIQ1Yxb1gvRWlGT1E3VmUzV2oxTFZDSlM3dGxHRG9IdDRiUm8ySm8vZ1Vla3JhTW4wVHo1NkRNaDdZdHN3cHFmCjUxTGpLTVprcExOb3Y0WVJmUEhJRVJtVThOM1NQSlRVNG1oQjRFYzdDbHd5U0o0Mzh3S0ZtYy84V3hxVDVuTDIKTlVwaGVBN2FibUNaZlFlWGxjQ0RVQWcwanh5NHcyVGRad3F0ZUlFTkhCY29xb2REQ0FhZWtSM3kxeUVCOWk5Wgp0NzA9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo= 
  usages:
  - digital signature
  - key encipherment
  - client auth
