apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: practicioner-csr
spec:
  groups:
  - system:authenticated
  request: <paste encoded value from  cat command>
  usages:
  - digital signature
  - key encipherment
  - client auth