apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: newuser-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVFNQTRHQTFVRUF3d0hibVYzZFhObGNqRVFNQTRHQTFVRUNnd0hiR1ZoY201bApjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNbnJXdnM5RmJCSzYxcCtiNlZwCnp2STRGRXlEVmJ2V3JTSWdLQnlTQnJjYkp2dGIxRjdaNk1iTSsrYXRwd2tvSEQyd3R4bTZjQlVRZ3dTY085c1UKYktjTzNDanFaN3BjTklHQTl2WmhPR1ZkdXNSYnV6N0pWQUZLZ3NWRS9yZkJnWGcrVXJtUjZiOTFXdURHaE1HSQpwZmV0eW9tN3FOSWdkb1p6QXFuS093NzJvU1RiVlY3UEVoNEJsdnppckFIbkttUEx4aGd5cm9QdWc0WjNYVVhRCkh1Z1JEdkdlVzRjbnkzWTcwQll1cnVreExlb3N5U2FwbDJzWWRZSXNYUkwvT0l2dmhwdytDc2NmeWZPbGJoOFEKVWtGZHk2YXFiQjN4TVRhUlpJTDBBczlPclltZnNZUzk2cUVVZElmTEJ3eDdYNDdsMmtHVFVBVllPN0R4NWhEdQp5cDhDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJ1L2sxQ1ZhTEFyZWlEamZzQXBDZTN6RngzCmFJNDF4L0dFQTNUTkZjVTRRY1RmRXl2TGYrQTR5Q0JsbEwxZWVrVW1sNDMxMW5EVXNoRDNZWjI5RStNaDR1UEsKYkUwOUlrbktkdHBUQ1VCd1NUVHdJSU13ZWVPRWYwcHpVbmNzeHBDb3ZJZHhaakYwem9DM1QvVGVRQ1kwTHBtaAo5dmMwYkJXSXV5RmxraCtzWGd3a3lMT1VBZ1Q1cEwzSnZXQ3FLWVd1M0Z3U041VFpLc0EvRzNiaEVzM3o5ZlZUCk91L1VZYjRoVm5aTEhndjhvZU4vVnl4R1IwTjRXSkxLbkZDYXJ0SUp4RTdCQ0s3MkhxdGcxWlc2RjBEaWhjTDgKNmRUdjdyb3Y1cUtwcVVNZWtUcERZZGt4VEs5VGJrUE93T0FMMmwydi84VWZEck1xQXcrMGVWcFJoanBzCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo= 
  usages:
  - digital signature
  - key encipherment
  - client auth
